[2023-12-04T22:39:39.767+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:39:39.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:39:39.773+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:39:39.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:39:39.829+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:39:39.820+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'financials_api_get'
[2023-12-04T22:39:39.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:39:39.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.106 seconds
[2023-12-04T22:40:10.450+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:10.456+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:40:10.530+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:10.527+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:10.631+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:10.613+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'financials_api_get'
[2023-12-04T22:40:10.634+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:10.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.350 seconds
[2023-12-04T22:40:20.457+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:20.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:40:20.461+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:20.461+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:20.502+0000] {logging_mixin.py:154} INFO - /opt
[2023-12-04T22:40:20.502+0000] {logging_mixin.py:154} INFO - ['/home/airflow/.local/bin', '/opt', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2023-12-04T22:40:20.512+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:20.506+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 13, in <module>
    from financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'financials_api_get'
[2023-12-04T22:40:20.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:20.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.084 seconds
[2023-12-04T22:40:50.631+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:50.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:40:50.635+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:50.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:50.653+0000] {logging_mixin.py:154} INFO - /opt
[2023-12-04T22:40:50.653+0000] {logging_mixin.py:154} INFO - ['/home/airflow/.local/bin', '/opt', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2023-12-04T22:40:50.664+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:40:50.658+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 13, in <module>
    from financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'financials_api_get'
[2023-12-04T22:40:50.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:40:50.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.067 seconds
[2023-12-04T22:41:20.870+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:41:20.871+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:41:20.873+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:41:20.873+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:41:20.891+0000] {logging_mixin.py:154} INFO - /opt
[2023-12-04T22:41:20.892+0000] {logging_mixin.py:154} INFO - ['/home/airflow/.local/bin', '/opt', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2023-12-04T22:41:20.899+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:41:20.895+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 13, in <module>
    from financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'financials_api_get'
[2023-12-04T22:41:20.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:41:20.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-04T22:44:41.952+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:44:41.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:44:41.956+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:44:41.956+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:44:43.313+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:44:43.519+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:44:43.519+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:44:43.543+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:44:43.543+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-03T00:00:00+00:00, run_after=2023-12-04T00:00:00+00:00
[2023-12-04T22:44:43.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 1.629 seconds
[2023-12-04T22:45:18.010+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:18.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:45:18.015+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:18.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:18.677+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:18.711+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:18.710+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:45:18.732+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:18.731+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:45:18.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.746 seconds
[2023-12-04T22:45:49.956+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:49.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:45:49.960+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:49.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:50.391+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:45:50.422+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:50.421+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:45:50.441+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:45:50.441+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:45:50.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.506 seconds
[2023-12-04T22:46:20.647+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:20.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:46:20.650+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:20.650+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:21.039+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:21.061+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:21.060+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:46:21.084+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:21.084+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:46:21.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.458 seconds
[2023-12-04T22:46:51.292+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:51.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:46:51.296+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:51.296+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:51.721+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:46:51.743+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:51.743+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:46:51.766+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:46:51.766+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:46:51.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.495 seconds
[2023-12-04T22:47:21.952+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:21.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:47:21.955+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:21.954+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:22.317+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:22.337+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:22.336+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:47:22.355+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:22.355+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:47:22.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.423 seconds
[2023-12-04T22:47:52.556+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:52.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:47:52.559+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:52.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:52.950+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:47:52.973+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:52.972+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:47:52.993+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:47:52.993+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:47:53.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.463 seconds
[2023-12-04T22:48:23.218+0000] {processor.py:157} INFO - Started process (PID=84) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:23.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:48:23.222+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:23.221+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:23.636+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:23.658+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:23.658+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:48:23.680+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:23.680+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:48:23.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.485 seconds
[2023-12-04T22:48:53.944+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:53.945+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:48:53.948+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:53.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:54.366+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:48:54.387+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:54.387+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:48:54.411+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:48:54.411+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:48:54.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.490 seconds
[2023-12-04T22:49:24.625+0000] {processor.py:157} INFO - Started process (PID=102) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:24.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:49:24.628+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:24.628+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:25.036+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:25.057+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:25.056+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:49:25.087+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:25.086+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:49:25.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.495 seconds
[2023-12-04T22:49:55.299+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:55.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:49:55.303+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:55.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:55.725+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:49:55.746+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:55.745+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:49:55.766+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:49:55.766+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:49:55.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.490 seconds
[2023-12-04T22:50:25.976+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:25.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:50:25.979+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:25.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:26.410+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:26.431+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:26.430+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:50:26.451+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:26.451+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:50:26.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.497 seconds
[2023-12-04T22:50:56.652+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:56.653+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:50:56.655+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:56.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:57.036+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:50:57.057+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:57.056+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:50:57.076+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:50:57.076+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:50:57.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.444 seconds
[2023-12-04T22:51:27.300+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:27.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:51:27.310+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:27.306+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:27.738+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:27.759+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:27.758+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:51:27.777+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:27.777+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:51:27.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.505 seconds
[2023-12-04T22:51:57.992+0000] {processor.py:157} INFO - Started process (PID=147) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:57.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:51:57.996+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:57.996+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:58.365+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:51:58.390+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:58.390+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:51:58.415+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:51:58.415+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:51:58.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.444 seconds
[2023-12-04T22:52:28.622+0000] {processor.py:157} INFO - Started process (PID=156) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:28.624+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:52:28.626+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:28.626+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:29.005+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:29.025+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:29.025+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:52:29.048+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:29.048+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:52:29.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.446 seconds
[2023-12-04T22:52:59.268+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:59.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:52:59.271+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:59.271+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:59.709+0000] {processor.py:839} INFO - DAG(s) dict_keys(['downloading_fundamentals']) retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:52:59.731+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:59.731+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-04T22:52:59.750+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:52:59.750+0000] {dag.py:3722} INFO - Setting next_dagrun for downloading_fundamentals to 2023-12-04T00:00:00+00:00, run_after=2023-12-05T00:00:00+00:00
[2023-12-04T22:52:59.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.505 seconds
[2023-12-04T22:53:00.800+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:00.801+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:53:00.803+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:53:00.803+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:00.848+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:53:00.841+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 5, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:53:00.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:00.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.087 seconds
[2023-12-04T22:53:30.990+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:30.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:53:30.993+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:53:30.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:31.016+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:53:31.011+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 5, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:53:31.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:53:31.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-04T22:54:01.245+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:01.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:54:01.249+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:54:01.248+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:01.277+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:54:01.272+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 5, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:54:01.278+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:01.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-04T22:54:31.419+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:31.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:54:31.423+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:54:31.422+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:31.448+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:54:31.444+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 5, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:54:31.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:54:31.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-04T22:55:01.643+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:01.644+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:55:01.645+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:55:01.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:01.670+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:55:01.666+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 5, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:55:01.671+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:01.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-04T22:55:11.717+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:11.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T22:55:11.719+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:55:11.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:11.767+0000] {logging_mixin.py:154} INFO - [2023-12-04T22:55:11.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T22:55:11.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T22:55:11.786+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.073 seconds
[2023-12-04T23:00:44.362+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:00:44.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:00:44.369+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:00:44.369+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:00:44.410+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:00:44.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:00:44.413+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:00:44.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.090 seconds
[2023-12-04T23:01:14.691+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:14.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:01:14.708+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:01:14.707+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:14.750+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:01:14.740+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:01:14.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:14.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.121 seconds
[2023-12-04T23:01:44.960+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:44.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:01:44.964+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:01:44.964+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:44.989+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:01:44.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:01:44.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:01:45.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.078 seconds
[2023-12-04T23:02:15.142+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:15.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:02:15.147+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:02:15.146+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:15.181+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:02:15.172+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:02:15.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:15.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.081 seconds
[2023-12-04T23:02:45.412+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:45.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:02:45.417+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:02:45.417+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:45.442+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:02:45.438+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:02:45.444+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:02:45.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.065 seconds
[2023-12-04T23:03:15.593+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:15.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:03:15.597+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:03:15.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:15.625+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:03:15.620+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:03:15.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:15.647+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.057 seconds
[2023-12-04T23:03:45.803+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:45.805+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:03:45.807+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:03:45.807+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:45.837+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:03:45.831+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:03:45.839+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:03:45.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.060 seconds
[2023-12-04T23:04:15.982+0000] {processor.py:157} INFO - Started process (PID=95) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:15.984+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:04:15.986+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:04:15.986+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:16.013+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:04:16.008+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:04:16.015+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:16.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-04T23:04:46.193+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:46.194+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:04:46.196+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:04:46.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:46.219+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:04:46.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:04:46.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:04:46.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-04T23:05:16.361+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:16.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:05:16.365+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:05:16.365+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:16.390+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:05:16.385+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:05:16.392+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:16.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-04T23:05:46.621+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:46.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:05:46.625+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:05:46.625+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:46.650+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:05:46.645+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:05:46.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:05:46.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-04T23:06:16.790+0000] {processor.py:157} INFO - Started process (PID=127) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:16.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:06:16.794+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:06:16.794+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:16.818+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:06:16.814+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:06:16.820+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:16.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-04T23:06:46.987+0000] {processor.py:157} INFO - Started process (PID=135) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:46.988+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:06:46.990+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:06:46.990+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:47.017+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:06:47.012+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:06:47.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:06:47.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-04T23:07:17.173+0000] {processor.py:157} INFO - Started process (PID=144) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:17.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:07:17.176+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:07:17.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:17.202+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:07:17.197+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:07:17.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:17.223+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-04T23:07:47.389+0000] {processor.py:157} INFO - Started process (PID=152) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:47.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:07:47.392+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:07:47.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:47.415+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:07:47.411+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:07:47.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:07:47.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-04T23:08:17.569+0000] {processor.py:157} INFO - Started process (PID=160) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:17.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:08:17.573+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:08:17.572+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:17.597+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:08:17.592+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:08:17.598+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:17.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-04T23:08:47.810+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:47.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-04T23:08:47.816+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:08:47.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:47.850+0000] {logging_mixin.py:154} INFO - [2023-12-04T23:08:47.844+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-04T23:08:47.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-04T23:08:47.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.091 seconds
